version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/zazzle
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build.serverless
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ./
          paths:
            - graphql-sam-deploy
  deploy:
    working_directory: ~/zazzle
    executor: aws-serverless/default
    steps:
      - checkout
      - aws-serverless/install
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
      - run:
          name: AWS sam pack deploy
          command: |
            ls -al
            sam package --template-file graphql-sam-deploy/template.json --output-template-file graphql-sam-deploy/sam-template.yml --s3-bucket zazzle-api
            sam deploy --template-file graphql-sam-deploy/sam-template.yml --stack-name zazzle-api --capabilities CAPABILITY_NAMED_IAM

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
